client_config_backend: file
client_config_file: "gdrive/client_secrets.json"

save_credentials: True
save_credentials_backend: file
save_credentials_file: "gdrive/credentials.json"

get_refresh_token: False

oauth_scope:
    - https://www.googleapis.com/auth/drive
